name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]
        xcode: ['Xcode_13.0', 'Xcode_14.0']
        exclude:
          - os: macos-11
            xcode: 'Xcode_14.0'
          - os: macos-12
            xcode: 'Xcode_13.0'     
    runs-on: ${{ matrix.os }}         
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: xcodebuild -enableCodeCoverage YES -scheme FioriSwiftUI-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' clean build test 
